name: Check for outdated dependencies

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run issue reporter script
        run: node .github/scripts/create-issue.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
